AmigoCarClient/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'home#search'
  get '/help', to: 'home#help'
  get '/about', to: 'home#about'
  get '/contact', to: 'home#contact'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :transactions
  resources :reservations



  root 'home#search'




end

AmigoCarClient/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  require 'savon'
  require 'will_paginate/array'
  require 'time'
  before_action :logged_in_user, only: %i[new create edit update]
  # before_action :correct_user,   only: %i[edit update]

  def new
    @user = session_user
    @transaction = Transaction.new({})
  end

  def index
    result = @client_transactions.call(:get_all_transactions, message: {
                                         'start_point' => params[:start_point],
                                         'end_point' => params[:end_point]
                                       })
    transactions_array = []
    hash_result = result.to_hash[:get_all_transactions_response]
    unless hash_result.nil?
      get_transactions_from_hash(hash_result[:transactions], transactions_array)
    end
    @transactions = transactions_array.paginate(page: params[:page], per_page: 15)
  end

  def show
    result = @client_transactions.call(:get_transaction_by_id, message: { id: params[:id] })
    hash_result = result.to_hash[:get_transaction_by_id_response]

    @transaction = Transaction.new(hash_result[:transaction])
    @user = User.new(hash_result[:user])
    @current_user = session_user
    @transaction.nb_free_seats = Integer(@transaction.nb_free_seats)
    @transaction.nb_reservations = Integer(@transaction.nb_reservations)
    passengers_array = []
    unless hash_result.nil?
      get_passengers_from_hash(hash_result[:passengers], passengers_array)
    end
    p passengers_array
    @passengers = passengers_array.paginate(page: params[:page], per_page: 15)
  end

  def create
    message_hash = transaction_params
    result = @client_transactions.call(:create_transaction, message: {
                                         transaction: {
                                           id: nil,
                                           'user_id' => message_hash[:user_id],
                                           'dep_city' => message_hash[:dep_city],
                                           'arrival_city' => message_hash[:arrival_city],
                                           'travel_date' => message_hash[:travel_date],
                                           price: message_hash[:price],
                                           'nb_reservations' => message_hash[:nb_reservations],
                                           'nb_free_seats' => message_hash[:nb_free_seats],
                                           'car_type' => message_hash[:car_type],
                                           luggage: message_hash[:luggage],
                                           smoking: message_hash[:smoking],
                                           animals: message_hash[:animals],
                                           cooling: message_hash[:cooling]
                                         }
                                       })
    id = result.to_hash[:create_transaction_response][:value]
    if id
      flash[:success] = 'Success!'
      redirect_to transaction_url(id)
    else
      flash[:danger] = 'Failure?!'
      render 'new'
    end
  end

  #
  #
  # NOT CHANGED
  #
  #

  def edit
    @user = current_user
    @transaction = Transaction.find(params[:id])
  end

  def update
    @transaction = Transaction.find(params[:id])
    if @transaction.update_attributes(transaction_params)
      flash[:success] = 'Travel updated'
      redirect_to @transaction
    else
      render 'edit'
    end
  end

  private

  def logged_in_user
    unless logged_in?
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @transaction = Transaction.find(params[:id])
    @user = User.find(@transaction.user_id)
    unless current_user?(@user)
      flash[:danger] = 'Unauthorized action !'
      redirect_to(root_url)
    end
  end

  def transaction_params
    params.permit(:dep_city, :arrival_city, :nb_free_seats,
                                        :travel_date, :price, :user_id, :nb_reservations,
                                        :luggage, :smoking, :animals, :car_type, :cooling,
                                        :created_at, :updated_at)
  end
end

AmigoCarClient/app/helpers/transactions_helper.rb
module TransactionsHelper

  def get_passengers_from_hash(hash_result, passengers_array)
    unless hash_result.nil?
      if hash_result.instance_of?(Hash)
        @passenger = User.new(hash_result)
        passengers_array << @passenger
      else
        hash_result.each do |user|
          @passenger = User.new(user)
          passengers_array << @passenger
        end
      end
    end
  end
end

AmigoCarClient/app/views/transactions/_transaction.html.erb
<li id="transaction-<%= transaction.id %> " class="transactions">
  <div class="linkable">
    <!--<!%= link_to gravatar_for(transaction.user, size: 50), transaction.user %>-->
    <!--<span class="user">-->
      <!--<!%= link_to transaction.user do %>-->
        <!--<!%= transaction.user.first_name %> <!%= transaction.user.name %>-->
      <!--<!% end %></span>-->
    <%= link_to transaction_url(transaction.id) do %>
        <div>
          <% date = Time.parse(transaction.travel_date.to_s) %>
          <span class="cities"><%= transaction.dep_city + " " %> &rArr; <%= " " + transaction.arrival_city %></span>
          <% if controller_name == "users" %>
              <span class="travel_date"> <%= date.strftime("On %A %e %B at %k:%M") %> </span>
          <% else %>
              <span class="travel_date"> <%= date.strftime("%k:%M") %> </span>
          <% end %>
          <span class="timestamp">Posted <%= time_ago_in_words(transaction.created_at) %> ago.</span>

        </div>

    <% end %>

  </div>

  <!% if @user && current_user.id == transaction.user_id %>
      <!--<span class="edit" style="text-align:center;"><!%= link_to "edit", edit_transaction_path(transaction),class:"btn btn-sm btn-primary centered"%></span>-->
  <!% end %>
</li>

AmigoCarClient/app/views/transactions/index.html.erb
<% provide(:title, 'Travels') %>

<h2>Find a trip here</h2>
<%= form_tag(transactions_path, :method => "get", id: "search-form") do %>
    <div class="input-box">
      <%= text_field_tag :start_point, params[:start_point], placeholder: "Start Point" %> &rArr; <%= text_field_tag :end_point, params[:end_point], placeholder: "Destination Point" %><br>
      <%= submit_tag "Search", class: "transaction_search", :name => nil %>
    </div>
<% end %>

<% if params[:start_point] %>
    <h2>Travels related to : <%= params[:start_point] %></h2>
<% else %>
    <h2>All travels</h2>
<% end %>


<% if @transactions.nil? %>
    <% if params[:start_point] %>
        <h4>Oups ! No travels corresponding</h4>
    <% else %>
        <h4>Oups ! No travels yet ! :'( </h4>
    <% end %>

<% else %>

    <%= will_paginate %>

    <% date = Time.parse(@transactions.first.travel_date.to_s)  rescue nil %>

    <div class="dateline"><%=h date.strftime("%A %e %B") %></div>

    <% @transactions.each do |transaction|
      if date.to_date === transaction.travel_date.to_date

      else
        date = Time.parse(transaction.travel_date.to_s) %>
            <div class="dateline"><%=h date.strftime("%A %e %B") %></div>
        <%end%>

        <ol class="transactions">
        </ol>

    <% end %>

    <%= will_paginate %>

<% end %>

AmigoCarClient/app/views/transactions/new.html.erb
<%= provide(:title,"New Trip") %>


<h1 xmlns:text-align="http://www.w3.org/1999/xhtml">Create a new trip</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with url: transactions_path do |f| %>

        <%= f.label :dep_city %>
        <%= f.text_field :dep_city, class: 'form-control' %>

        <%= f.label :arrival_city %>
        <%= f.text_field :arrival_city, class: 'form-control' %>

        <%= f.label :travel_date %>
        <%= f.datetime_field :travel_date, class: 'form-control' %>

        <%= f.label :price %>
        <%= f.number_field :price, class: 'form-control' %>

        <%= f.label :nb_free_seats %>
        <%= f.number_field :nb_free_seats, class: 'form-control' %>

        <%= f.hidden_field :user_id, class: 'form-control', value: @user.id%>

        <%= f.hidden_field :nb_reservations, class: 'form-control', value: 0%>

        <h4> Preferences</h4>

        <div class="row">
          <div class="col-md-3">
            <%= label_tag(:smoking, "Smoking") %>
            <%= f.check_box(:smoking)  %>

          </div>
          <div class="col-md-6" >
            <%= label_tag(:luggage, "Luggage or Big Backpack") %>
            <%= f.check_box(:luggage)  %>
          </div>
          <div class="col-md-3">
            <%= label_tag(:animals, "Animals Allowed") %>
            <%= f.check_box(:animals)  %>
          </div>
        </div>


        <h4> Your Car</h4>


        <%= f.select(:car_type,[['Hatchback Car', 'Hatchback'], ['Sedan car', 'Sedan']]) %>

        <%= label_tag(:cooling, "Does your car have cooling?") %>

        <%= f.check_box(:cooling)  %>





        <%= f.submit "Create this trip", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

AmigoCarClient/app/views/transactions/show.html.erb
<% provide(:title, @transaction.dep_city + ' to ' + @transaction.arrival_city) %>

<h1>Ride from <%= @transaction.dep_city %> to <%= @transaction.arrival_city %></h1>
<h2><%= Time.parse(@transaction.travel_date).strftime("On %A %e %B at %k:%M") %></h2>
<div class="center jumbotron">

  <div class="row">
    <div class="col-md-9">
      <section class="travel_info">

        <div class="row">
          <div class="col-md-6">
            <section class="map">
              <h3><%= @transaction.dep_city %> to <%= @transaction.arrival_city %></h3>

              <img src="http://maps.google.com/maps/api/staticmap?size=255x255&key=AIzaSyD9B8xCa3pfY_iqeb889ips99g3fA_iWNE&maptype=roadmap&sensor=false&markers=color:blue|label:A|'+<%= @transaction.dep_city %>+',QC&markers=color:purple|label:B|'+<%= @transaction.arrival_city %>+',QC"
                   alt="Static, Marked Map of '+<%= @transaction.dep_city %>+', Quebec and '+<%= @transaction.arrival_city %>+', Quebec with no Center and Zoom"> </img>
            </section>
          </div>
          <div class="col-md-6">
            <section class="preferences">
              <h3>Preferences</h3>
              <div class="row">
                <% if @transaction.smoking %>
                    <%= image_tag("smoking.png", alt: " smoking",size: "32") %>
                    Smoking
                <%else %>
                    <%= image_tag("no smoking.png", alt: "no smoking",size: "32") %>
                    Non-Smoking
                <%end%>
              </div>
              <div class="row">
                <% if @transaction.luggage %>
                    <%= image_tag("Luggage.png", alt: "Luggage",size: "32") %>
                    Big backpack/luggage
                <%else %>
                    <%= image_tag("Backpack.png", alt: "Backpack",size: "32") %>
                    Small Backpack
                <%end%>
              </div>
              <div class="row">

                <% if @transaction.animals %>
                    <%= image_tag("Animals.png", alt: "Animals",size: "32") %>
                    Animals Allowed
                <%else %>
                    <%= image_tag("no Animals.png", alt: "No Animals",size: "32") %>
                    No Animals
                <%end%>
              </div>
              <div class="row">

                <% if @transaction.cooling %>
                    <%= image_tag("Cooling.png", alt: "Cooling",size: "32") %>
                    Air conditioning
                <%else %>
                    No Air conditioning
                <%end%>
              </div>




            </section>
          </div>

        </div>
      </section>
    </div>
    <div class="col-md-3">
      <section class="user">
        <h3>Information about the driver</h3>
        <div class="row">
          <%= render partial: 'users/user', locals: {user: @user}  %>
        </div>


        <div class="row">
          <h4> Car type: </h4>
          <div class="row">
            <%= @transaction.car_type %>
          </div>
          <div class="row">
            <%if @transaction.car_type==("Sedan")%>
                <%= image_tag("Berline.png", alt: "Sedan Car",size: "125") %>
            <%else if @transaction.car_type==("Hatchback") %>
                    <%= image_tag("citadine.png", alt: "Hatchback Car",size: "125") %>
                <%end %>
            <%end%>
          </div>

        </div>


      </section>
    </div>

  </div>


  <div class="row">
    <div class="col-md-4">
      <section class="price">
        <h3>Price</h3>
        <%= @transaction.price %> $ <br><br>
        <% if logged_in? %>

            <% if @transaction.nb_free_seats < 1 %>
                <%= link_to "Select & Pay", transactions_path, method: :get, class: "btn btn-primary",
                            data: { confirm: "Sorry ! This trip is already full, you will be redirected" }%>
            <% elsif @transaction.user_id == @current_user.id %>
                <%= link_to "Select & Pay", transaction_url(@transaction.id), method: :get, class: "btn btn-primary",
                            data: { confirm: "Sorry ! You can not reserve a seat for your own trip" }%>
            <% else %>
                <%= form_with  url: reservations_path(transaction_id: @transaction.id) do |f| %>
                    <%= f.select :seats_selected, (1..@transaction.nb_free_seats) %>
                    <%= f.submit "Select & Pay", class: "btn btn-primary", data: {confirm: "Pay 5$ per person and continue ?"} %>
                <% end %>

            <% end %>
        <% else %>
            <%= link_to "Log in", login_path, class: "btn btn-primary" %>
        <% end %>
      </section>
    </div>
    <div class="col-md-4 col-md-offset-3">
      <section class="passengers">
        <h3>Others passengers (<%=@transaction.nb_reservations%> /
          <%=@transaction.nb_free_seats + @transaction.nb_reservations%>)</h3>
        <% if @passengers %>
            <% @passengers.each do |user|%>
                <p>
                  <%= render partial: 'users/user', locals: {user: user}  %>
                </p>

            <% end %>
        <% else %>
            No others passengers at this moment !
        <% end %>
      </section>
    </div>

  </div>

</div>