AmigoCarClient/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'home#search'
  get '/help', to: 'home#help'
  get '/about', to: 'home#about'
  get '/contact', to: 'home#contact'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :transactions
  resources :reservations



  root 'home#search'




end

AmigoCarClient/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def search; end

  def help; end

  def about; end

  def contact; end
end

AmigoCarClient/app/views/home/about.html.erb
<% provide(:title, "About") %>
<div class="center jumbotron">
  <h1>About</h1>
  <p>
    AmigoCar Project
  </p>
</div>

AmigoCarClient/app/views/home/contact.html.erb
<% provide(:title, "Contact") %>


<div class="center jumbotron">
  <h1>Contact page</h1>
  <h2> Hello, We are anonymous </h2>
  <p> Contact us here</p>
  <%= link_to "Contact", '#', class: "btn btn-lg btn-primary" %>


</div>

AmigoCarClient/app/views/home/help.html.erb
<% provide(:title, "Help") %>
<div class="center jumbotron">
  <h1>Help</h1>
  <b><s>WIP</s></b> Not Anymore in Progress

</div>

AmigoCarClient/app/views/home/search.html.erb
<% provide(:title, "Search") %>
<div class="center jumbotron">
  <h1>Welcome to AmigoCar</h1>
  <h2> Here you can search or post a trip </h2>
  <%= link_to "Sign up Now", new_user_path, class: "btn btn-lg btn-primary" %>
</div>