AmigoCarClient/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'home#search'
  get '/help', to: 'home#help'
  get '/about', to: 'home#about'
  get '/contact', to: 'home#contact'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :transactions
  resources :reservations



  root 'home#search'




end

AmigoCarClient/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &#169; AmigoCar
    by Romain Vanmarcke et Sylvain Pryfer
  </small>

  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>

</footer>

AmigoCarClient/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "AmigoCAR", home_path, id: "logo" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right ">
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "Find a ride", transactions_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Create a trip", new_transaction_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= @session_user.first_name + " "+ @session_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", user_url(@session_user.id) %></li>
                <li><%= link_to "Settings", edit_user_url(@session_user.id) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>

      </ul>
    </div>
  </div>



</header>

AmigoCarClient/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

AmigoCarClient/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmigoCarClient  | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <!--IE9 - utilities -->
    <%= render 'layouts/shim' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer'%>

  </div>
  </body>
</html>