AmigoCarClient/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'home#search'
  get '/help', to: 'home#help'
  get '/about', to: 'home#about'
  get '/contact', to: 'home#contact'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :transactions
  resources :reservations



  root 'home#search'




end

AmigoCarClient/app/models/user.rb
class User
  extend ActiveModel::Model
  # has_many :transactions
  # has_many :reservations

  # before_save { self.email = email.downcase }

  attr_accessor :id,
                :name,
                :first_name,
                :telephone,
                :email,
                :password_digest,
                :created_at,
                :updated_at,
                :admin

  def initialize(hash)
    @id = hash[:id]
    @name = hash[:name] unless hash[:name].nil?
    @first_name = hash[:first_name] unless hash[:first_name].nil?
    @telephone = hash[:telephone] unless hash[:telephone].nil?
    @email = hash[:email] unless hash[:email].nil?
    @password_digest = hash[:password_digest] unless hash[:password_digest].nil?
    @created_at = hash[:created_at] unless hash[:created_at].nil?
    @updated_at = hash[:updated_at] unless hash[:updated_at].nil?
    @admin = hash[:admin] unless hash[:admin].nil?
  end


  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def authenticate(unencrypted_password)
    BCrypt::Password.new(password_digest).is_password?(unencrypted_password) && self
  end
end

AmigoCarClient/app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'savon'
  require 'will_paginate/array'

  before_action :logged_in_user, only: [:index, :edit, :update,:destroy]
  # before_action :correct_user,   only: [:edit, :update]



  def new
    @user = User.new({})
  end

  def edit
    @user = session_user
  end

  def index
    result = @client_users.call(:get_all_users)
    temp = []
    result.to_hash[:get_all_users_response][:users].each do |user|
      @user = User.new(user)
      temp.push(@user)
    end
    p temp
    @users = temp.paginate(page: params[:page])
  end

  def show
    result = @client_users.call(:get_user_by_id, message: { id: params[:id] })
    @user = User.new(result.to_hash[:get_user_by_id_response][:user])

    transactions_array = []
    passenger_transactions_array = []
    hash_result = result.to_hash[:get_user_by_id_response]
    unless hash_result.nil?
      get_transactions_from_hash(hash_result[:transactions], transactions_array)
      get_transactions_from_hash(hash_result[:passenger_transactions], passenger_transactions_array)
    end
    @transactions = transactions_array.paginate(page: params[:page], per_page: 15)
    @reservations = passenger_transactions_array.paginate(page: params[:page], per_page: 15)
  end

  def create
    if params[:password_confirmation] != params[:password]
      flash[:danger] = 'Password and confirmation are differents'
      redirect_to new_user_path
    else
      message_hash = user_params
      message_hash[:password_digest] = User.digest(message_hash[:password])
      result = @client_users.call(:create_user, message: {
                                    user: {
                                      id: nil,
                                      name: message_hash[:name],
                                      'first_name' => message_hash[:first_name],
                                      telephone: message_hash[:telephone],
                                      email: message_hash[:email],
                                      'password_digest' => message_hash[:password_digest]
                                    }
                                  })
      id = result.to_hash[:create_user_response][:value]
      if id
        @user = User.new(id: id, name: message_hash[:name],
                         first_name: message_hash[:first_name])
        log_in @user
        flash[:success] = 'Welcome to AmigoCar!'
        redirect_to user_url(id)
      else
        flash[:danger] = 'An error occured !'
        redirect_to new_user_path
      end
    end
  end

  def update
    if params[:password_confirmation] != params[:password]
      flash[:danger] = 'Password and confirmation are differents'
      redirect_to edit_user_path
    else
      message_hash = user_params
      message_hash[:password_digest] = User.digest(message_hash[:password])
      result = @client_users.call(:update_user, message: {
                                    user: {
                                      id: message_hash[:id],
                                      name: message_hash[:name],
                                      'first_name' => message_hash[:first_name],
                                      telephone: message_hash[:telephone],
                                      email: message_hash[:email],
                                      'password_digest' => message_hash[:password_digest]
                                    }
                                  })
      id = result.to_hash[:update_user_response][:value]
      if id
        flash[:success] = 'Profile updated'
        redirect_to user_url(id)
      else
        flash[:danger] = 'An error occurred !'
        redirect_to edit_user_path
      end

    end
  end

  private

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)
      flash[:danger] = "Unauthorized action !"
      redirect_to(root_url)
    end
  end

  def user_params
    params.permit(:id, :name, :first_name, :email, :password, :password_confirmation, :telephone, :commit, :authenticity_token, :utf8)
  end
end

AmigoCarClient/app/helpers/users_helper.rb
module UsersHelper

#  def gravatar_for(user,options = { size: 80 })
#    puts user
#    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
#    size = options[:size]
#    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=identicon"
#    image_tag(gravatar_url, alt: user.name, class: "gravatar")
#  end

  def get_transactions_from_hash(hash_result, transactions_array)
    unless hash_result.nil?
      if hash_result.instance_of?(Hash)
        @transaction = Transaction.new(hash_result)
        transactions_array << @transaction
      else
        hash_result.each do |transaction|
          @transaction = Transaction.new(transaction)
          transactions_array << @transaction
        end
      end
    end
  end

end

AmigoCarClient/app/views/users/_user.html.erb
<%= gravatar_for user, size: 50 %>
<%= link_to user_url(user.id) do %>
  <%= user.first_name %> <%= user.name %>
<% end %>

AmigoCarClient/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with url: user_url(@user.id), method: :patch do |f| %>
        <!%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>


        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>


        <%= f.label :telephone %>
        <%= f.text_field :telephone, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <!--<div class="gravatar_edit">-->
      <!--<!%= gravatar_for @user %>-->
      <!--<a href="http://gravatar.com/emails" target="_blank">change</a>-->
    <!--</div>-->
  </div>
</div>

AmigoCarClient/app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    <li>

      <%= gravatar_for user, size: 50 %>
      <%= link_to user_path(user.id) do %>
          <%= user.first_name %> <%= user.name %>
      <% end %>
      <!% if logged_in? && @current_user.admin && !current_user?(user) %>
           <!%= link_to "delete", user, method: :delete,
                        data: { confirm: "You sure?" } %>
      <!% end %>
    </li>
  <% end %>

</ul>
<%= will_paginate %>

AmigoCarClient/app/views/users/new.html.erb
<%= provide(:title,"Sign up") %>


<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with url: users_path do |f| %>

        <!%= render 'shared/error_messages' %>

        <%= f.label :name %><a color="red">  *</a>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>

        <%= f.label :email %><a color="red">  *</a>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :telephone %>
        <%= f.telephone_field :telephone, class: 'form-control' %>

        <%= f.label :password %><a color="red">  *</a>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %><a color="red">  *</a>
        <%= f.password_field :password_confirmation, class: 'form-control' %>


        <a color="red">* obligatory</a>
        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

AmigoCarClient/app/views/users/show.html.erb
<% provide(:title, @user.name + "'s profile") %>
<div class="jumbotron">

  <h3 class="center">
    PROFILE
  </h3>


  <div class="row ">
    <aside class="col-md-4">
      <section class="user_info">

        <%= gravatar_for(@user, size: 80) %>
        <%= @user.name %>
        <%= @user.first_name %><br/>
        <%= @user.email %><br/>

        <%= @user.telephone %>


      </section>
    </aside>


    <div class="col-md-4">
      <% if @transactions.any? %>
        <h3>Your rides as driver (<%= @transactions.count %>)</h3>
        <ol class="transactions">
          <% @transactions.each do |transaction| %>
          <%= render partial: 'transactions/transaction', locals: {transaction: transaction}  %>
          <% end %>
        </ol>
        <%= will_paginate @transactions %>
      <% end %>
    </div>

    <div class="col-md-4">
      <% if @reservations.any? %>
        <h3>Your rides as passenger (<%= @reservations.count %>)</h3>
        <ol class="transactions">
          <% @reservations.each do |transaction| %>
              <%= render partial: 'transactions/transaction', locals: {transaction: transaction}  %>
            <!% @reservations.each do |reservation| %>
              <!% if reservation.transaction_id == transaction.id %>
                <!% @reservation = reservation %>
              <!% end %>
            <!% end %>
            <!% if logged_in? && current_user?(@user) %>
              <!--<span class="edit" style="text-align:center;"><!%= link_to "delete", @reservation, method: :delete, class:"btn btn-sm btn-primary centered"%></span>-->
            <!% end %>
          <% end %>
        </ol>
        <%= will_paginate @reservations %>
      <% end %>
    </div>

  </div>
</div>